"""Runs the browser-free JavaScript suite through the documented command.

The frontend has logic in it — dispatch, validation, response construction, a
reveal handshake — and reading a diff is not a test of any of that. This module
executes it under Node with a small DOM shim (``tests/js/dom.mjs``), which is the
whole of the frontend tooling: no package manager, no lockfile, no browser
download, nothing added to anybody's environment.

There is exactly one way to run the suite, and this module uses it rather than
reimplementing it::

    uv run python tools/run_frontend_tests.py

Fixtures are generated by that script from the real component registry through
the real :func:`learning_studio.components.build_component`, so the JavaScript is
exercised against the exact learner projection the API returns. Documenting a
bare ``node --test …`` would be documenting a command that fails, because the
fixtures have to exist first.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from learning_studio.components import COMPONENT_TYPES
from tests.component_examples import CANARY, example

NODE = shutil.which("node")

TOOLS = Path(__file__).resolve().parent.parent / "tools"


def _runner():
    """The one implementation, imported rather than copied."""
    if str(TOOLS) not in sys.path:
        sys.path.insert(0, str(TOOLS))
    import run_frontend_tests

    return run_frontend_tests


def test_the_fixtures_carry_no_hidden_field_before_node_is_asked_to_check():
    """The Python side of the same assertion the JavaScript makes.

    If this fails, the JavaScript suite's canary tests are vacuous — they would
    be looking for a marker that was never in the input.
    """
    fixtures = _runner().component_fixtures()
    rendered = json.dumps(fixtures)

    assert CANARY not in rendered
    assert set(fixtures) == set(COMPONENT_TYPES)
    # And the examples really do contain canaries to leak, so the check has teeth.
    assert CANARY in json.dumps({name: example(name) for name in COMPONENT_TYPES})


def test_the_fixture_generator_serves_no_canonical_identifier():
    """The payloads the frontend suite asserts against must be the safe ones.

    Two properties at once, and the second is the one a JavaScript test could not
    check for itself: the arrangement is not the answer, and the identifiers on
    the card are aliases, so nothing in the fixture can be sorted back into the
    order the manifest was authored in.
    """
    from learning_studio.components import ANSWER_BEARING_ORDER, build_component

    fixtures = _runner().component_fixtures()

    for component_type, rules in ANSWER_BEARING_ORDER.items():
        source = build_component(example(component_type), "component")
        served = fixtures[component_type]["payload"]["content"]
        for rule in rules:
            shown = [entry["id"] for entry in served[rule.field]]
            canonical = [entry["id"] for entry in source.content[rule.field]]
            assert len(shown) == len(canonical)
            assert not set(shown) & set(canonical), (
                f"{component_type}.{rule.field} was handed over with canonical identifiers"
            )


def _declared_identifiers(node, found: set[str]) -> None:
    """Every ``id`` anywhere in a content structure."""
    if isinstance(node, dict):
        if isinstance(node.get("id"), str):
            found.add(node["id"])
        for value in node.values():
            _declared_identifiers(value, found)
    elif isinstance(node, list):
        for value in node:
            _declared_identifiers(value, found)


def test_no_fixture_contains_a_canonical_content_identifier():
    """Across every type, not only the answer-bearing ones.

    An id is a name an author chose, and authors name things after what they are:
    `correct`, `distractor-1`, `t1`. None of that reaches a learner.
    """
    import json

    from learning_studio.components import build_component

    fixtures = _runner().component_fixtures()

    for component_type in COMPONENT_TYPES:
        source = build_component(example(component_type), "component")
        declared: set[str] = set()
        _declared_identifiers(source.content, declared)

        served = json.dumps(fixtures[component_type]["payload"].get("content", {}))
        for identifier in declared:
            assert f'"{identifier}"' not in served, (
                f"{component_type} served the canonical identifier {identifier}"
            )


@pytest.mark.skipif(NODE is None, reason="node is not installed; the frontend suite needs it")
def test_the_documented_frontend_command_succeeds():
    """The exact command the README tells a contributor to run.

    Run as a subprocess, from the repository root, with nothing pre-arranged —
    so if it needs an environment variable somebody has to set by hand, this
    fails. The previous version of the documentation named a bare
    ``node --test …`` that could not work for that reason.
    """
    completed = subprocess.run(
        [sys.executable, "tools/run_frontend_tests.py"],
        cwd=Path(__file__).resolve().parent.parent,
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )

    assert completed.returncode == 0, completed.stdout + completed.stderr
    assert "# fail 0" in completed.stdout, completed.stdout[-2000:]


@pytest.mark.skipif(NODE is None, reason="node is not installed; the frontend suite needs it")
def test_the_suite_refuses_to_run_without_its_fixtures():
    """Rather than passing vacuously, which is the failure that matters.

    A suite that quietly skipped its assertions when ``LS_PAYLOADS`` was unset
    would look identical to a passing one.
    """
    environment = {key: value for key, value in os.environ.items() if key != "LS_PAYLOADS"}
    completed = subprocess.run(
        [NODE, "--test", "tests/js/renderers.test.mjs"],
        cwd=Path(__file__).resolve().parent.parent,
        env=environment,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )

    assert completed.returncode != 0
    assert "LS_PAYLOADS" in completed.stdout + completed.stderr


def test_every_suite_file_is_actually_run():
    """A new suite nobody wired up would otherwise sit there passing nothing."""
    runner = _runner()
    on_disk = sorted(
        f"tests/js/{p.name}" for p in (TOOLS.parent / "tests" / "js").glob("*.test.mjs")
    )

    assert runner.suite_files() == on_disk
    assert len(on_disk) >= 2


def test_node_is_available_wherever_the_suite_is_expected_to_run():
    """A skipped frontend suite is a frontend with no tests, so say so loudly.

    Skipping is right for a contributor who has no Node installed — the Python
    package does not need it — but CI installs it, and a silent skip there would
    mean the JavaScript stopped being tested without anybody noticing.
    """
    if os.environ.get("CI"):
        assert NODE is not None, "CI must run the frontend suite, and node is missing"


def test_the_frontend_and_the_runtime_agree_on_the_selector_shape():
    """Two implementations of one rule, kept honest against each other.

    The runtime issues launch ids and refuses anything else; the page refuses
    to *send* anything else. If the two patterns drift, either valid launches
    stop opening or the page starts posting strings the runtime will not read.
    """
    from pathlib import Path

    from learning_studio.runtime.grants import LAUNCH_ID_PATTERN
    from learning_studio.telegram_launch import LAUNCH_FRAGMENT_KEY

    app_js = (
        Path(__file__).resolve().parent.parent / "learning_studio" / "web" / "static" / "app.js"
    ).read_text(encoding="utf-8")

    assert f'LAUNCH_FRAGMENT_KEY = "{LAUNCH_FRAGMENT_KEY}"' in app_js
    # The Python pattern, written the way JavaScript spells it.
    assert "/^[A-Za-z0-9_-]{16,64}$/" in app_js
    assert LAUNCH_ID_PATTERN.pattern == r"\A[A-Za-z0-9_-]{16,64}\Z"


def test_the_page_never_posts_an_experience_id():
    """On a launched runtime the server derives the exercise from the grant."""
    from pathlib import Path

    app_js = (
        Path(__file__).resolve().parent.parent / "learning_studio" / "web" / "static" / "app.js"
    ).read_text(encoding="utf-8")

    # Checked against what the code *reads*, not what the comments mention:
    # the docstring names `start_param` in order to explain why it is not used,
    # and a substring scan would read that explanation as a violation.
    for reader in ('get("start_param")', ".start_param", "experience_id:"):
        assert reader not in app_js, reader
