"""Runs the browser-free JavaScript suite through the documented command.

The frontend has logic in it — dispatch, validation, response construction, a
reveal handshake — and reading a diff is not a test of any of that. This module
executes it under Node with a small DOM shim (``tests/js/dom.mjs``), which is the
whole of the frontend tooling: no package manager, no lockfile, no browser
download, nothing added to anybody's environment.

There is exactly one way to run the suite, and this module uses it rather than
reimplementing it::

    uv run python tools/run_frontend_tests.py

Fixtures are generated by that script from the real component registry through
the real :func:`learning_studio.components.build_component`, so the JavaScript is
exercised against the exact learner projection the API returns. Documenting a
bare ``node --test …`` would be documenting a command that fails, because the
fixtures have to exist first.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from learning_studio.components import COMPONENT_TYPES
from tests.component_examples import CANARY, example

NODE = shutil.which("node")

TOOLS = Path(__file__).resolve().parent.parent / "tools"


def _runner():
    """The one implementation, imported rather than copied."""
    if str(TOOLS) not in sys.path:
        sys.path.insert(0, str(TOOLS))
    import run_frontend_tests

    return run_frontend_tests


def test_the_fixtures_carry_no_hidden_field_before_node_is_asked_to_check():
    """The Python side of the same assertion the JavaScript makes.

    If this fails, the JavaScript suite's canary tests are vacuous — they would
    be looking for a marker that was never in the input.
    """
    fixtures = _runner().component_fixtures()
    rendered = json.dumps(fixtures)

    assert CANARY not in rendered
    assert set(fixtures) == set(COMPONENT_TYPES)
    # And the examples really do contain canaries to leak, so the check has teeth.
    assert CANARY in json.dumps({name: example(name) for name in COMPONENT_TYPES})


def test_the_fixture_generator_shuffles_every_answer_bearing_order():
    """The fixtures the frontend sees must not be the ones that leak.

    Generated through the real projection, so this is the same guarantee
    ``tests/test_answer_order_privacy.py`` makes of the server — restated here
    because these are the payloads the JavaScript suite asserts against.
    """
    from learning_studio.components import ANSWER_BEARING_ORDER, build_component

    fixtures = _runner().component_fixtures()

    for component_type, fields in ANSWER_BEARING_ORDER.items():
        source = build_component(example(component_type), "component")
        for field_name in fields:
            shown = [
                entry["id"] for entry in fixtures[component_type]["payload"]["content"][field_name]
            ]
            original = [entry["id"] for entry in source.content[field_name]]
            assert sorted(shown) == sorted(original)
            assert shown != original, f"{component_type}.{field_name} was handed over in order"


@pytest.mark.skipif(NODE is None, reason="node is not installed; the frontend suite needs it")
def test_the_documented_frontend_command_succeeds():
    """The exact command the README tells a contributor to run.

    Run as a subprocess, from the repository root, with nothing pre-arranged —
    so if it needs an environment variable somebody has to set by hand, this
    fails. The previous version of the documentation named a bare
    ``node --test …`` that could not work for that reason.
    """
    completed = subprocess.run(
        [sys.executable, "tools/run_frontend_tests.py"],
        cwd=Path(__file__).resolve().parent.parent,
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )

    assert completed.returncode == 0, completed.stdout + completed.stderr
    assert "# fail 0" in completed.stdout, completed.stdout[-2000:]


@pytest.mark.skipif(NODE is None, reason="node is not installed; the frontend suite needs it")
def test_the_suite_refuses_to_run_without_its_fixtures():
    """Rather than passing vacuously, which is the failure that matters.

    A suite that quietly skipped its assertions when ``LS_PAYLOADS`` was unset
    would look identical to a passing one.
    """
    environment = {key: value for key, value in os.environ.items() if key != "LS_PAYLOADS"}
    completed = subprocess.run(
        [NODE, "--test", "tests/js/renderers.test.mjs"],
        cwd=Path(__file__).resolve().parent.parent,
        env=environment,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )

    assert completed.returncode != 0
    assert "LS_PAYLOADS" in completed.stdout + completed.stderr


def test_every_suite_file_is_actually_run():
    """A new suite nobody wired up would otherwise sit there passing nothing."""
    runner = _runner()
    on_disk = sorted(
        f"tests/js/{p.name}" for p in (TOOLS.parent / "tests" / "js").glob("*.test.mjs")
    )

    assert runner.suite_files() == on_disk
    assert len(on_disk) >= 2


def test_node_is_available_wherever_the_suite_is_expected_to_run():
    """A skipped frontend suite is a frontend with no tests, so say so loudly.

    Skipping is right for a contributor who has no Node installed — the Python
    package does not need it — but CI installs it, and a silent skip there would
    mean the JavaScript stopped being tested without anybody noticing.
    """
    if os.environ.get("CI"):
        assert NODE is not None, "CI must run the frontend suite, and node is missing"
