/*
 * Loading the real frontend files into the fake DOM.
 *
 * The scripts are read from `learning_studio/web/static/` and evaluated in a
 * `node:vm` context whose `window` is the shim -- the same files the server
 * sends, byte for byte, with no build step and no transpiling. If a test here
 * passes, it passed against the shipped code.
 *
 * The skeleton the application expects is built from the ids actually present in
 * `index.html`, so a renamed element breaks these tests instead of only breaking
 * the phone. `tests/test_mini_app_frontend.py` closes the loop from the other
 * direction: every id `app.js` asks for must exist in the document.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

import { createWindow } from "./dom.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = join(HERE, "..", "..");
export const STATIC_DIR = join(REPO_ROOT, "learning_studio", "web", "static");

export function staticSource(name) {
  return readFileSync(join(STATIC_DIR, name), "utf8");
}

/** The learner payloads generated by the Python side, keyed by component type. */
export function payloads() {
  const path = process.env.LS_PAYLOADS;
  if (!path) {
    throw new Error(
      "LS_PAYLOADS is not set, so there are no component fixtures to test against.\n" +
        "Run the suite with:\n\n" +
        "    uv run python tools/run_frontend_tests.py\n\n" +
        "That command generates the fixtures from the component registry and hands " +
        "them over, which is why a bare `node --test` cannot work on its own."
    );
  }
  return JSON.parse(readFileSync(path, "utf8"));
}

/** The marker every hidden field in the fixtures carries. */
export function canaryPrefix() {
  return process.env.LS_CANARY || "ZZCANARY";
}

/** Ids the document declares, so the skeleton matches the shipped shell. */
export function documentIds() {
  const markup = staticSource("index.html").replace(/<!--[\s\S]*?-->/g, "");
  return [...markup.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]);
}

const contexts = new WeakMap();

/**
 * Run one shipped script in this window's context.
 *
 * The context is created once per window and cached: contextifying the same
 * object twice is not the same as loading two scripts into one page, and the
 * three files genuinely do share a global.
 */
function evaluate(win, filename) {
  if (!contexts.has(win)) {
    contexts.set(win, vm.createContext(win));
  }
  vm.runInContext(staticSource(filename), contexts.get(win), { filename });
  return win;
}

/**
 * A window with `i18n.js` and `renderers.js` loaded — enough for the renderers,
 * without booting the application.
 */
export function loadRenderers(overrides = {}) {
  const win = createWindow(overrides);
  evaluate(win, "i18n.js");
  evaluate(win, "icons.js");
  evaluate(win, "renderers.js");
  return win;
}

/**
 * A window with the whole frontend loaded and the application booted.
 *
 * `app.js` boots itself the moment it is loaded, which is what it does in a
 * browser too, so the stubs have to be in place first. The returned promise is
 * the boot, exposed by the application for exactly this reason.
 */
export function loadApp({ telegram = null, fetch = null, location = null } = {}) {
  const win = createWindow();
  for (const id of documentIds()) {
    const node = win.document.createElement("div");
    node.setAttribute("id", id);
    win.document.body.appendChild(node);
  }
  if (telegram) {
    win.Telegram = { WebApp: telegram };
  }
  if (fetch) {
    win.fetch = fetch;
  }
  if (location) {
    win.location = location;
  }

  evaluate(win, "i18n.js");
  evaluate(win, "icons.js");
  evaluate(win, "renderers.js");
  evaluate(win, "app.js");
  return { win, booted: win.LearningStudioApp.booted || Promise.resolve() };
}

/** A translator, for asserting against the strings a card should show. */
export function translatorFor(win, locale) {
  return win.LearningStudioI18n.translator(locale);
}

/**
 * A render context, with the image loader the application would have injected.
 *
 * `requested` records what a card asked for, which is how the tests check that
 * a renderer goes through the loader instead of building a URL of its own.
 */
export function renderContext(win, options = {}) {
  const {
    locale = "en",
    contentLocale = null,
    images = "ok",
    reveal = null,
  } = options;
  const requested = [];
  const revealed = [];
  return {
    t: translatorFor(win, locale),
    uiLocale: translatorFor(win, locale).locale,
    contentLocale,
    requested,
    revealed,
    loadImage(assetRef) {
      requested.push(assetRef);
      return images === "ok"
        ? Promise.resolve(`blob:fake/${assetRef}`)
        : Promise.reject(new Error("no image"));
    },
    /**
     * Stands in for the authenticated reveal call.
     *
     * Defaults to refusing, so a renderer that somehow displayed the back
     * without asking would not be able to hide behind a permissive fake.
     */
    reveal(attempt) {
      revealed.push(attempt);
      if (typeof reveal === "function") {
        return reveal(attempt);
      }
      return Promise.reject({ message: "no reveal configured" });
    },
  };
}

/**
 * Re-create a value with this realm's prototypes.
 *
 * Objects built inside the `vm` context have a different `Object.prototype`, and
 * `assert.deepStrictEqual` compares prototypes — so a response that is
 * structurally identical to the expectation still fails. Round-tripping through
 * JSON is also the honest comparison: what the application does with a response
 * is `JSON.stringify` it into a request body.
 */
export function plain(value) {
  return value === undefined ? undefined : JSON.parse(JSON.stringify(value));
}

/** Let every already-resolved promise run its callbacks. */
export async function settle(times = 8) {
  for (let index = 0; index < times; index += 1) {
    await Promise.resolve();
  }
}
