/*
 * The renderers, executed.
 *
 * The payload fixtures are generated by `tests/test_frontend_js.py` from the
 * trusted component registry itself, so these tests run against exactly what
 * the server would send -- including the fact that every hidden field in the
 * source components carries a canary that must appear in none of it.
 */

import assert from "node:assert/strict";
import test from "node:test";

import { check, click, press, type, pointerEnvironment, pointer, orderingGeometry } from "./dom.mjs";
import { completeCard } from "./complete.mjs";
import {
  canaryPrefix,
  loadRenderers,
  payloads,
  plain,
  renderContext,
  settle,
} from "./harness.mjs";

const FIXTURES = payloads();
const CANARY = canaryPrefix();
const FLASHCARD_BACK = "yama";
const TYPES = Object.keys(FIXTURES).sort();

function fresh(options) {
  const win = loadRenderers();
  return { win, api: win.LearningStudioRenderers, ctx: renderContext(win, options) };
}

function renderType(componentType, options) {
  const { win, api, ctx } = fresh(options);
  const component = FIXTURES[componentType];
  const card = api.render(component, ctx);
  return { win, api, ctx, component, card };
}

/**
 * A card that can actually be finished, reveal included.
 *
 * The default fake `reveal` *refuses*, so a renderer that displayed the back
 * without asking could not hide behind a permissive stub. The sweeps below are
 * about completability rather than about authorisation, so they get a reveal that
 * succeeds — and every authorisation question is asked by
 * `tests/test_mini_app_reveal.py` against the real route.
 */
function renderCompletable(componentType) {
  return renderType(componentType, {
    reveal: (attempt) => Promise.resolve({ back: FLASHCARD_BACK, attempt: attempt }),
  });
}

function inputsOf(card, kind) {
  return card.element.byTag("input").filter((input) => input.type === kind);
}

// ── Dispatch ──────────────────────────────────────────────────────────────

test("every component type in the registry has a renderer", () => {
  const { api } = fresh();

  assert.deepEqual(
    TYPES.filter((name) => !api.SUPPORTED_TYPES.includes(name)),
    [],
    "a registry type has no renderer; add one or state the gap deliberately"
  );
});

test("dispatch selects the renderer named by the component type", () => {
  for (const componentType of TYPES) {
    const { card } = renderType(componentType);

    assert.equal(card.element.getAttribute("data-component-type"), componentType);
    assert.equal(card.unsupported, false, `${componentType} rendered as unsupported`);
    assert.equal(typeof card.read, "function");
  }
});

test("an unknown component type renders an unsupported card, not an empty one", () => {
  const { api, ctx } = fresh();

  const card = api.render(
    { component_id: "x", type: "holographic_interpretive_dance", payload: { prompt: "Do it" } },
    ctx
  );

  assert.equal(card.unsupported, true);
  assert.match(card.element.textContent, /cannot be shown here/);
  assert.match(card.element.textContent, /holographic_interpretive_dance/);
});

test("an unsupported card cannot be submitted as an answer", () => {
  const { api, ctx } = fresh();

  const card = api.render({ component_id: "x", type: "not_a_type", payload: {} }, ctx);
  const read = card.read();

  assert.equal(read.ok, false);
  assert.ok(read.error);
});

test("a malformed payload costs one card, not the session", () => {
  const { api, ctx } = fresh();

  // A known type whose content is missing everything the renderer needs.
  const card = api.render({ component_id: "x", type: "multiple_choice", payload: {} }, ctx);

  assert.equal(card.unsupported, true);
  assert.equal(card.read().ok, false);
});

// ── Nothing hidden reaches the card ───────────────────────────────────────

test("no canary from any hidden field appears in any rendered card", async () => {
  for (const componentType of TYPES) {
    const { card, component } = renderType(componentType);
    await settle();

    assert.ok(
      !JSON.stringify(component).includes(CANARY),
      `${componentType}: the payload itself carried a canary`
    );
    assert.ok(
      !card.element.serialize().includes(CANARY),
      `${componentType}: a hidden field reached the DOM`
    );
  }
});

test("a completed card submits no canary either", async () => {
  for (const componentType of TYPES) {
    const { card, component } = renderCompletable(componentType);
    await settle();
    completeCard(card.element, component.payload);
    await settle();
    const read = card.read();

    assert.ok(
      !JSON.stringify(read).includes(CANARY),
      `${componentType}: a canary reached the submitted response`
    );
  }
});

test("no card exposes an answer key, rubric, hint, or branch field", async () => {
  for (const componentType of TYPES) {
    const { card } = renderType(componentType);
    await settle();
    // The type discriminator and the icon key are the app's own markers and
    // legitimately contain words like "rubric" (`rubric_response` is a
    // component type, and its icon family is named after it). Everything else
    // in the card came from the payload.
    const markup = card.element
      .serialize()
      .replace(/ data-component-type="[^"]*"/, "")
      .replace(/ data-icon="[^"]*"/g, "");

    for (const forbidden of ["evaluation", "rubric", "branching", "reference_solution"]) {
      assert.ok(!markup.includes(forbidden), `${componentType} mentions ${forbidden}`);
    }
  }
});

// ── Every card can be answered ────────────────────────────────────────────

//: Some cards are answerable the moment they appear, and deliberately so:
//: `code_response` seeds its editor with the declared starter code,
//: `error_correction` seeds it with the flawed passage to be corrected, and an
//: ordering card arrives already in *some* order — probably the wrong one, but a
//: complete answer, which is how every ordering interface behaves. For these,
//: "refuses an empty submission" is inverted rather than dropped.
const PRESEEDED = new Set([
  "code_response",
  "error_correction",
  "process_flow",
  "sentence_order",
  "sequence_order",
  "timeline",
]);

test("every card refuses an empty submission before it accepts a full one", async () => {
  for (const componentType of TYPES) {
    const { card, component } = renderCompletable(componentType);
    await settle();

    const empty = card.read();
    const touched = completeCard(card.element, component.payload);
    await settle();
    const full = card.read();

    const offered =
      touched.radios +
      touched.checkboxes +
      touched.texts +
      touched.selects +
      touched.hotspots +
      touched.orderings +
      touched.reveals;
    assert.ok(offered > 0, `${componentType} rendered nothing to answer`);
    if (PRESEEDED.has(componentType)) {
      assert.equal(empty.ok, true, `${componentType} should arrive already seeded`);
    } else {
      assert.equal(empty.ok, false, `${componentType} accepted an empty answer`);
      assert.ok(empty.error, `${componentType} refused without saying why`);
    }
    assert.equal(full.ok, true, `${componentType} refused a completed card: ${full.error}`);
    assert.ok(full.response && typeof full.response === "object");
  }
});

test("a pre-seeded card starts from the text the component supplied", () => {
  const code = renderType("code_response");
  const correction = renderType("error_correction");

  assert.equal(
    code.card.element.byTag("textarea")[0].value,
    code.component.payload.content.starter_code
  );
  assert.equal(
    correction.card.element.byTag("textarea")[0].value,
    correction.component.payload.content.text
  );
});

test("a submitted response stays inside the API's bounds", async () => {
  // The API caps a response at depth 4, 100 items per container, and 4000
  // characters per string. A renderer that produced something deeper would be
  // refused with a 400 that looked like a server fault.
  function depthOf(value, depth = 0) {
    if (Array.isArray(value)) {
      return Math.max(depth, ...value.map((item) => depthOf(item, depth + 1)));
    }
    if (value && typeof value === "object") {
      return Math.max(depth, ...Object.values(value).map((item) => depthOf(item, depth + 1)));
    }
    if (typeof value === "string") {
      assert.ok(value.length <= 4000);
    }
    return depth;
  }

  for (const componentType of TYPES) {
    const { card, component } = renderCompletable(componentType);
    await settle();
    completeCard(card.element, component.payload);
    await settle();
    const read = card.read();

    assert.ok(depthOf(read.response) <= 4, `${componentType} nests too deeply`);
  }
});

// ── The required renderers, one response shape at a time ──────────────────

test("multiple_choice submits the chosen option id", () => {
  const { card, component } = renderType("multiple_choice");
  const options = component.payload.content.options;

  check(inputsOf(card, "radio")[1]);

  assert.deepEqual(plain(card.read()), { ok: true, response: { option_id: options[1].id } });
});

test("multiple_choice shows every option and refuses none chosen", () => {
  const { card, component } = renderType("multiple_choice");
  const options = component.payload.content.options;

  assert.equal(inputsOf(card, "radio").length, options.length);
  for (const option of options) {
    assert.ok(card.element.textContent.includes(option.text));
  }
  assert.equal(card.read().ok, false);
});

test("multi_select submits every chosen option and drops one un-chosen", () => {
  const { card, component } = renderType("multi_select");
  const options = component.payload.content.options;
  const boxes = inputsOf(card, "checkbox");

  check(boxes[0]);
  check(boxes[1]);
  check(boxes[1], false);
  check(boxes[2]);

  assert.deepEqual(plain(card.read().response), { option_ids: [options[0].id, options[2].id] });
});

test("true_false submits a boolean", () => {
  const first = renderType("true_false");
  check(inputsOf(first.card, "radio")[0]);
  assert.deepEqual(plain(first.card.read().response), { value: true });

  const second = renderType("true_false");
  check(inputsOf(second.card, "radio")[1]);
  assert.deepEqual(plain(second.card.read().response), { value: false });
});

test("true_false shows the statement it is asking about", () => {
  const { card, component } = renderType("true_false");

  assert.ok(card.element.textContent.includes(component.payload.content.statement));
});

test("fill_blank submits one entry per blank, keyed by blank id", () => {
  const { card, component } = renderType("fill_blank");
  const blanks = component.payload.content.blanks;
  const fields = card.element.byTag("input");

  assert.equal(fields.length, blanks.length);
  fields.forEach((field, index) => type(field, `answer ${index}`));

  assert.deepEqual(plain(card.read().response.blanks),
    blanks.map((blank, index) => ({ blank_id: blank.id, text: `answer ${index}` }))
  );
});

test("fill_blank refuses a partly filled passage", () => {
  const { card } = renderType("fill_blank");

  assert.equal(card.read().ok, false);
});

test("fill_blank renders its passage as text, gaps included", () => {
  const { card, component } = renderType("fill_blank");
  const passage = component.payload.content.text;

  // The placeholder is replaced by a field, so the literal braces are gone and
  // the surrounding prose survives.
  assert.ok(!card.element.textContent.includes("{{"));
  assert.ok(card.element.textContent.includes(passage.split("{{")[0].trim()));
});

test("short_answer submits text", () => {
  const { card } = renderType("short_answer");

  type(card.element.byTag("input")[0], "the mitochondrial matrix");

  assert.deepEqual(plain(card.read().response), { text: "the mitochondrial matrix" });
});

test("ordering submits the current order and the buttons change it", () => {
  const { card, component } = renderType("sequence_order");
  const steps = component.payload.content.steps;

  assert.deepEqual(plain(card.read().response.order),
    steps.map((step) => step.id)
  );

  // The first row's second button is "move down".
  const rows = card.element.byTag("li");
  const downButton = rows[0].byTag("button")[1];
  downButton.dispatchEvent({ type: "click" });

  const swapped = steps.map((step) => step.id);
  [swapped[0], swapped[1]] = [swapped[1], swapped[0]];
  assert.deepEqual(plain(card.read().response.order), swapped);
});

test("ordering fallback needs no pointer and every control is a button", () => {
  const { card } = renderType("sentence_order");
  const rows = card.element.byTag("li");

  for (const row of rows) {
    assert.equal(row.byTag("button").length, 2);
  }
  assert.equal(rows[0].byTag("button")[0].disabled, true, "the first row cannot move up");
  assert.equal(
    rows[rows.length - 1].byTag("button")[1].disabled,
    true,
    "the last row cannot move down"
  );
});

test("matching submits a pair per left item", () => {
  const { card, component } = renderType("matching");
  const left = component.payload.content.left;
  const right = component.payload.content.right;
  const selects = card.element.byTag("select");

  assert.equal(selects.length, left.length);
  assert.equal(card.read().ok, false, "an unmatched row is not an answer");

  selects.forEach((select, index) => {
    select.value = right[index % right.length].id;
  });

  assert.deepEqual(plain(card.read().response.pairs),
    left.map((entry, index) => ({
      left_id: entry.id,
      right_id: right[index % right.length].id,
    }))
  );
});

test("flashcard ships without the back of the card anywhere in it", async () => {
  const { card, component } = renderType("flashcard");
  await settle();

  // The payload has no `back` field to leak, and nothing the renderer built
  // contains one — not the text, not an attribute, not a prefilled value.
  assert.ok(!JSON.stringify(component.payload).includes("back"));
  assert.ok(!card.element.serialize().includes(FLASHCARD_BACK));
  assert.ok(card.element.textContent.includes(component.payload.content.front));
});

test("flashcard offers an explicit, keyboard-operable turn-over", () => {
  const { card } = renderType("flashcard");
  const buttons = card.element.byTag("button");
  const turn = buttons.find((button) => button.className.includes("primary"));

  assert.ok(turn, "there is no turn-over control");
  assert.equal(turn.getAttribute("type"), "button", "it must not submit a form");
  assert.match(turn.textContent, /Turn the card over/);
});

test("flashcard refuses to turn over with nothing written", async () => {
  const { card, ctx } = renderType("flashcard");
  const turn = card.element.byTag("button").find((b) => b.className.includes("primary"));

  click(turn);
  await settle();

  assert.deepEqual(ctx.revealed, [], "a reveal was requested with no attempt behind it");
  assert.match(card.element.textContent, /Write what you remember/);
});

test("flashcard cannot be submitted before it has been turned over", () => {
  const { card } = renderType("flashcard");
  const radios = inputsOf(card, "radio");

  type(card.element.byTag("textarea")[0], "yama");
  check(radios[2]);

  const read = card.read();
  assert.equal(read.ok, false);
  assert.match(read.error, /Turn the card over/);
});

test("turning the card over asks the server and shows only what it returned", async () => {
  const { card, ctx } = renderType("flashcard", {
    reveal: (attempt) => Promise.resolve({ back: FLASHCARD_BACK, attempt: attempt }),
  });
  const turn = card.element.byTag("button").find((b) => b.className.includes("primary"));

  type(card.element.byTag("textarea")[0], "yama, I think");
  click(turn);
  await settle();

  assert.deepEqual(ctx.revealed, ["yama, I think"]);
  assert.ok(card.element.textContent.includes(FLASHCARD_BACK));
  assert.equal(turn.hidden, true, "the turn-over control is spent");
});

test("the recall is frozen once the card has been turned over", async () => {
  const { card } = renderType("flashcard", {
    reveal: (attempt) => Promise.resolve({ back: FLASHCARD_BACK, attempt: attempt }),
  });
  const area = card.element.byTag("textarea")[0];

  type(area, "my honest attempt");
  click(card.element.byTag("button").find((b) => b.className.includes("primary")));
  await settle();

  // The server froze it; the field says so rather than inviting an edit that
  // would then be refused.
  assert.equal(area.readOnly, true);
  assert.equal(area.getAttribute("aria-readonly"), "true");
  assert.equal(area.value, "my honest attempt");
});

test("flashcard submits the frozen recall and the self-rating", async () => {
  const { card } = renderType("flashcard", {
    reveal: (attempt) => Promise.resolve({ back: FLASHCARD_BACK, attempt: attempt }),
  });

  type(card.element.byTag("textarea")[0], "yama");
  click(card.element.byTag("button").find((b) => b.className.includes("primary")));
  await settle();

  assert.equal(card.read().ok, false, "a turned card with no rating is not answered");
  check(inputsOf(card, "radio")[2]);

  assert.deepEqual(plain(card.read().response), { text: "yama", self_rating: "good" });
});

test("a refused reveal says so and leaves the card answerable later", async () => {
  const { card } = renderType("flashcard", {
    reveal: () => Promise.reject({ message: "Turn the card over again." }),
  });
  const turn = card.element.byTag("button").find((b) => b.className.includes("primary"));

  type(card.element.byTag("textarea")[0], "yama");
  click(turn);
  await settle();

  assert.match(card.element.textContent, /Turn the card over again/);
  assert.equal(turn.disabled, false, "a failed reveal must be retryable");
  assert.equal(card.read().ok, false);
});

test("the revealed answer is announced without stealing focus", async () => {
  const { card } = renderType("flashcard", {
    reveal: (attempt) => Promise.resolve({ back: FLASHCARD_BACK, attempt: attempt }),
  });

  const panel = card.element.all().find((node) => node.className === "reveal");
  assert.equal(panel.getAttribute("aria-live"), "polite");
});

test("image_observation asks the loader for its asset and submits text", async () => {
  const { card, ctx, component } = renderType("image_observation");
  await settle();

  assert.deepEqual(ctx.requested, [component.payload.content.image.asset_ref]);
  const image = card.element.byTag("img")[0];
  assert.equal(image.getAttribute("src"), `blob:fake/${component.payload.content.image.asset_ref}`);
  assert.equal(image.getAttribute("alt"), component.payload.content.image.alt_text);

  type(card.element.byTag("textarea")[0], "thick walls throughout");
  assert.deepEqual(plain(card.read().response), { text: "thick walls throughout" });
});

test("a failed image keeps the alternative text and says what happened", async () => {
  const { card } = renderType("image_observation", { images: "broken" });
  await settle();

  assert.equal(card.element.byTag("img").length, 0, "a broken image is not left in the page");
  assert.match(card.element.textContent, /could not be loaded/);
});

test("scenario_choice shows the situation and submits an option", () => {
  const { card, component } = renderType("scenario_choice");

  assert.ok(card.element.textContent.includes(component.payload.content.situation));
  check(inputsOf(card, "radio")[0]);

  assert.deepEqual(plain(card.read().response), {
    option_id: component.payload.content.options[0].id,
  });
});

test("confidence_rating offers the declared scale and submits a number", () => {
  const { card, component } = renderType("confidence_rating");
  const content = component.payload.content;
  const radios = inputsOf(card, "radio");

  assert.equal(radios.length, content.scale_max - content.scale_min + 1);
  check(radios[1]);

  assert.deepEqual(plain(card.read().response), { rating: content.scale_min + 1 });
});

test("reflection submits one response per prompt", () => {
  const { card, component } = renderType("reflection");
  const prompts = component.payload.content.prompts;
  const areas = card.element.byTag("textarea");
  const written = prompts.map((_prompt, index) => `answer ${index} ` + "word ".repeat(30).trim());

  assert.equal(areas.length, prompts.length);
  for (const prompt of prompts) {
    assert.ok(card.element.textContent.includes(prompt));
  }
  areas.forEach((area, index) => type(area, written[index]));

  assert.deepEqual(plain(card.read().response.responses), written);
});

test("a multi-prompt minimum counts the whole response, not each field", () => {
  const { card, component } = renderType("reflection");
  const areas = card.element.byTag("textarea");
  const minimum = component.payload.content.min_words;

  assert.ok(minimum > 1, "this fixture is only interesting with a real minimum");

  // Just under, spread across the fields: refused.
  type(areas[0], "word ".repeat(minimum - 2).trim());
  type(areas[1], "word");
  assert.equal(card.read().ok, false);

  // The same total plus one word: accepted, rather than demanding the minimum
  // twice over.
  type(areas[1], "word word");
  assert.equal(card.read().ok, true);
});

// ── The three additional renderers ────────────────────────────────────────

test("diagram shows its callouts and submits text", async () => {
  const { card, component } = renderType("diagram");
  await settle();

  for (const callout of component.payload.content.callouts || []) {
    assert.ok(card.element.textContent.includes(callout.text));
  }
  type(card.element.byTag("textarea")[0], "the node sits low in the septum");
  assert.equal(card.read().ok, true);
});

test("hotspot submits normalised coordinates and takes arrow keys", async () => {
  const { card } = renderType("hotspot");
  await settle();
  const surface = card.element.byTag("button").find((node) => node.className.includes("hotspot"));

  assert.equal(card.read().ok, false, "no point placed is not an answer");

  press(surface, "ArrowRight");
  const first = card.read().response.points[0];
  assert.equal(first.x, 0.55, "the first press starts from the centre and steps 5%");
  assert.equal(first.y, 0.5);

  press(surface, "ArrowDown", { shiftKey: true });
  const second = card.read().response.points[0];
  assert.equal(second.y, 0.51, "shift steps by 1%");
});

test("hotspot coordinates stay inside the unit square", async () => {
  const { card } = renderType("hotspot");
  await settle();
  const surface = card.element.byTag("button").find((node) => node.className.includes("hotspot"));

  for (let index = 0; index < 40; index += 1) {
    press(surface, "ArrowRight");
    press(surface, "ArrowUp");
  }
  const point = card.read().response.points[0];

  assert.equal(point.x, 1);
  assert.equal(point.y, 0);
});

test("timeline orders events and shows their date labels", () => {
  const { card, component } = renderType("timeline");
  const events = component.payload.content.events;

  assert.deepEqual(plain(card.read().response.order),
    events.map((event) => event.id)
  );
  for (const event of events) {
    assert.ok(card.element.textContent.includes(event.text));
    if (event.date_label) {
      assert.ok(card.element.textContent.includes(event.date_label));
    }
  }
});

// ── Generated content is text, never code ─────────────────────────────────

test("code_response shows the starter code as text and submits a string", () => {
  const { card, component } = renderType("code_response");
  const area = card.element.byTag("textarea")[0];

  assert.equal(area.value, component.payload.content.starter_code || "");
  assert.equal(area.getAttribute("spellcheck"), "false");
  assert.match(card.element.textContent, /never run/);

  type(area, "def solve():\n    return 42");
  const read = card.read();

  assert.equal(typeof read.response.code, "string");
  assert.equal(read.response.code, "def solve():\n    return 42");
});

test("a component whose text looks like markup is rendered as text", () => {
  const { api, ctx } = fresh();
  const hostile = "<img src=x onerror=alert(1)> </script><b>bold</b>";

  const card = api.render(
    {
      component_id: "x",
      type: "true_false",
      payload: { prompt: hostile, content: { statement: hostile } },
    },
    ctx
  );

  // Present as characters, absent as structure: no element was created for it.
  assert.ok(card.element.textContent.includes(hostile));
  assert.equal(card.element.byTag("img").length, 0);
  assert.equal(card.element.byTag("b").length, 0);
  assert.equal(card.element.byTag("script").length, 0);
});

// ── Localization ──────────────────────────────────────────────────────────

test("the interface is localized while the exercise content is not", () => {
  const french = renderType("multi_select", { locale: "fr" });
  const english = renderType("multi_select", { locale: "en" });
  const optionText = french.component.payload.content.options[0].text;

  assert.match(french.card.element.textContent, /Choisissez/);
  assert.match(english.card.element.textContent, /Choose/);
  // The option itself is the exercise, and reads the same in both.
  assert.ok(french.card.element.textContent.includes(optionText));
  assert.ok(english.card.element.textContent.includes(optionText));
});

test("an unknown locale falls back to English rather than to a half-translation", () => {
  const { win } = fresh();
  const i18n = win.LearningStudioI18n;

  assert.equal(i18n.resolveLocale("kl-GL"), "en");
  assert.equal(i18n.resolveLocale(""), "en");
  assert.equal(i18n.resolveLocale(null), "en");
  assert.equal(i18n.resolveLocale(undefined), "en");
  assert.equal(i18n.resolveLocale(42), "en");
  assert.equal(i18n.translator("kl-GL")("action.submit"), i18n.STRINGS.en["action.submit"]);
});

test("a regional locale falls back to its base language", () => {
  const { win } = fresh();
  const i18n = win.LearningStudioI18n;

  assert.equal(i18n.resolveLocale("fr-CA"), "fr");
  assert.equal(i18n.resolveLocale("FR_ca"), "fr");
  assert.equal(i18n.resolveLocale("es-419"), "es");
  assert.equal(i18n.translator("fr-CA")("action.submit"), i18n.STRINGS.fr["action.submit"]);
});

test("a missing key degrades to English and then to the key itself", () => {
  const { win } = fresh();
  const i18n = win.LearningStudioI18n;

  assert.equal(i18n.translator("fr")("no.such.key"), "no.such.key");
});

test("placeholders are interpolated and an unknown one is left alone", () => {
  const { win } = fresh();
  const t = win.LearningStudioI18n.translator("en");

  assert.equal(t("progress.text", { position: 2, count: 5 }), "Card 2 of 5");
  assert.equal(t("progress.text", {}), "Card {position} of {count}");
});

// ── Accessibility ─────────────────────────────────────────────────────────

test("every field has a label or an accessible name", async () => {
  for (const componentType of TYPES) {
    const { card } = renderType(componentType);
    await settle();

    const labelled = new Set(
      card.element
        .byTag("label")
        .map((label) => label.getAttribute("for"))
        .filter(Boolean)
    );

    for (const field of card.element.byTag("input").concat(card.element.byTag("textarea"))) {
      if (field.type === "radio" || field.type === "checkbox") {
        // Wrapped in their own <label>, which is the accessible name.
        assert.equal(field.parentNode.tagName, "label", `${componentType}: bare radio`);
        continue;
      }
      const named = labelled.has(field.getAttribute("id")) || field.getAttribute("aria-label");
      assert.ok(named, `${componentType}: a field has no accessible name`);
    }
    for (const select of card.element.byTag("select")) {
      assert.ok(
        labelled.has(select.getAttribute("id")) || select.getAttribute("aria-label"),
        `${componentType}: a select has no accessible name`
      );
    }
  }
});

test("every image carries alternative text", async () => {
  for (const componentType of TYPES) {
    const { card } = renderType(componentType);
    await settle();

    for (const image of card.element.byTag("img")) {
      assert.ok(image.getAttribute("alt"), `${componentType}: an image has no alt text`);
    }
  }
});

test("a card that declares reduced motion is marked so the stylesheet can obey", () => {
  const { api, ctx } = fresh();

  const card = api.render(
    {
      component_id: "x",
      type: "true_false",
      payload: {
        prompt: "Still?",
        content: { statement: "Yes." },
        accessibility: { reduced_motion: true },
      },
    },
    ctx
  );

  assert.equal(card.element.getAttribute("data-reduced-motion"), "true");
});

test("component accessibility metadata is shown, not silently dropped", () => {
  const { api, ctx } = fresh();

  const card = api.render(
    {
      component_id: "x",
      type: "true_false",
      payload: {
        prompt: "Was that clear?",
        content: { statement: "It was." },
        accessibility: {
          caption: "A caption a reader needs.",
          transcript: "Every word that was said.",
          keyboard_alternative: "Press T or F.",
          long_description: "The full description.",
        },
      },
    },
    ctx
  );
  const shown = card.element.textContent;

  assert.ok(shown.includes("A caption a reader needs."));
  assert.ok(shown.includes("Every word that was said."));
  assert.ok(shown.includes("Press T or F."));
  assert.ok(shown.includes("The full description."));
});

test("word bounds are enforced before a request is made", () => {
  const { api, ctx } = fresh();

  const card = api.render(
    {
      component_id: "x",
      type: "free_response",
      payload: { prompt: "Explain.", content: { min_words: 5, max_words: 8 } },
    },
    ctx
  );
  const area = card.element.byTag("textarea")[0];

  type(area, "too short");
  assert.equal(card.read().ok, false);

  type(area, "one two three four five six");
  assert.equal(card.read().ok, true);

  type(area, "one two three four five six seven eight nine");
  assert.equal(card.read().ok, false);
});

// ── A failed image still says what the picture showed ─────────────────────

test("a failed image renders its alt text as visible content", async () => {
  const { card, component } = renderType("image_observation", { images: "broken" });
  await settle();
  const altText = component.payload.content.image.alt_text;

  assert.equal(card.element.byTag("img").length, 0, "a broken <img> was left in the page");
  assert.ok(
    card.element.textContent.includes(altText),
    "the alt text is promised and then not shown — the exact defect this replaced"
  );
  assert.match(card.element.textContent, /could not be loaded/);
});

test("an image that arrives but will not decode falls back the same way", async () => {
  // The other failure mode: the fetch succeeds, the element fires `error`.
  const { card, component } = renderType("image_observation");
  await settle();
  const image = card.element.byTag("img")[0];

  image.dispatchEvent({ type: "error" });

  assert.equal(card.element.byTag("img").length, 0);
  assert.ok(card.element.textContent.includes(component.payload.content.image.alt_text));
});

test("the alt fallback carries no server error text and no asset identifier", async () => {
  const { card, component } = renderType("image_observation", { images: "broken" });
  await settle();
  const shown = card.element.serialize();

  assert.ok(!shown.includes("no image"), "a raw failure reason reached the page");
  assert.ok(!shown.includes(component.payload.content.image.asset_ref));
});

test("a long description stays separate from the alt text", async () => {
  const { api, ctx } = fresh({ images: "broken" });
  const card = api.render(
    {
      component_id: "x",
      type: "image_observation",
      payload: {
        prompt: "Describe it.",
        content: {
          image: {
            asset_ref: "asset-1",
            alt_text: "A short alternative.",
            long_description: "A much longer account of the same picture.",
          },
        },
      },
    },
    ctx
  );
  await settle();

  assert.ok(card.element.textContent.includes("A short alternative."));
  assert.ok(card.element.textContent.includes("A much longer account of the same picture."));
  // The long form is behind a disclosure; the short form is not.
  assert.equal(card.element.byTag("details").length, 1);
  assert.equal(card.element.byTag("details")[0].textContent.includes("A short alternative."), false);
});

test("an image with no long description still shows its alt text", async () => {
  const { card } = renderType("hotspot", { images: "broken" });
  await settle();

  assert.equal(card.element.byTag("details").length, 0);
  assert.ok(card.element.textContent.includes("A cross-section of the human heart, unlabelled."));
});

// ── The hotspot's structure ───────────────────────────────────────────────

function hotspotSurface(card) {
  return card.element.byTag("button").find((node) => node.className.includes("hotspot"));
}

test("no interactive element is nested inside the hotspot control", async () => {
  const { api, ctx } = fresh();
  const card = api.render(
    {
      component_id: "x",
      type: "hotspot",
      payload: {
        prompt: "Point at it.",
        content: {
          image: {
            asset_ref: "asset-1",
            alt_text: "A diagram.",
            long_description: "A much longer account.",
          },
        },
      },
    },
    ctx
  );
  await settle();
  const surface = hotspotSurface(card);

  for (const tag of ["button", "a", "input", "select", "textarea", "details", "summary"]) {
    assert.deepEqual(
      surface
        .all()
        .filter((node) => node !== surface && node.tagName === tag)
        .map((node) => node.tagName),
      [],
      `a <${tag}> is nested inside the hotspot button`
    );
  }
});

test("captions and long descriptions live outside the hotspot control", async () => {
  const { api, ctx } = fresh();
  const card = api.render(
    {
      component_id: "x",
      type: "hotspot",
      payload: {
        prompt: "Point at it.",
        content: {
          image: { asset_ref: "a", alt_text: "A diagram.", long_description: "The long form." },
        },
      },
    },
    ctx
  );
  await settle();

  assert.ok(!hotspotSurface(card).textContent.includes("The long form."));
  assert.ok(card.element.textContent.includes("The long form."));
});

test("the hotspot control has an accessible name and describes its own value", async () => {
  const { card } = renderType("hotspot");
  await settle();
  const surface = hotspotSurface(card);

  assert.ok(surface.getAttribute("aria-label"));
  assert.ok(surface.getAttribute("aria-describedby"));
});

test("hotspot coordinates are measured against the image, not the whole card", async () => {
  const { card } = renderType("hotspot");
  await settle();
  const surface = hotspotSurface(card);
  const image = card.element.byTag("img")[0];

  // A 200×100 picture somewhere down the page, with prose above it.
  image.getBoundingClientRect = () => ({ left: 40, top: 300, width: 200, height: 100 });

  surface.dispatchEvent({ type: "click", clientX: 140, clientY: 350 });

  assert.deepEqual(plain(card.read().response.points[0]), { x: 0.5, y: 0.5 });
});

test("a longer description does not move the coordinate", async () => {
  // The regression: measuring the button meant measuring the prose too, so the
  // same tap landed somewhere else once an author wrote more.
  const results = [];
  for (const longDescription of ["Short.", "A very much longer description ".repeat(20)]) {
    const { api, ctx } = fresh();
    const card = api.render(
      {
        component_id: "x",
        type: "hotspot",
        payload: {
          prompt: "Point.",
          content: {
            image: { asset_ref: "a", alt_text: "A diagram.", long_description: longDescription },
          },
        },
      },
      ctx
    );
    await settle();
    const image = card.element.byTag("img")[0];
    image.getBoundingClientRect = () => ({ left: 0, top: 0, width: 400, height: 200 });
    hotspotSurface(card).dispatchEvent({ type: "click", clientX: 100, clientY: 50 });
    results.push(plain(card.read().response.points[0]));
  }

  assert.deepEqual(results[0], results[1]);
  assert.deepEqual(results[0], { x: 0.25, y: 0.25 });
});

test("hotspot coordinates are clamped into the unit square", async () => {
  const { card } = renderType("hotspot");
  await settle();
  const image = card.element.byTag("img")[0];
  image.getBoundingClientRect = () => ({ left: 0, top: 0, width: 100, height: 100 });

  hotspotSurface(card).dispatchEvent({ type: "click", clientX: -50, clientY: 400 });

  assert.deepEqual(plain(card.read().response.points[0]), { x: 0, y: 1 });
});

test("a resized image surface maps the same tap to the same fraction", async () => {
  for (const width of [100, 1000]) {
    const { card } = renderType("hotspot");
    await settle();
    const image = card.element.byTag("img")[0];
    image.getBoundingClientRect = () => ({ left: 0, top: 0, width: width, height: width });
    hotspotSurface(card).dispatchEvent({
      type: "click",
      clientX: width * 0.75,
      clientY: width * 0.25,
    });

    assert.deepEqual(plain(card.read().response.points[0]), { x: 0.75, y: 0.25 });
  }
});

test("pointer and keyboard produce the same coordinate shape", async () => {
  const pointer = renderType("hotspot");
  await settle();
  const image = pointer.card.element.byTag("img")[0];
  image.getBoundingClientRect = () => ({ left: 0, top: 0, width: 100, height: 100 });
  hotspotSurface(pointer.card).dispatchEvent({ type: "click", clientX: 55, clientY: 50 });

  const keyboard = renderType("hotspot");
  await settle();
  press(hotspotSurface(keyboard.card), "ArrowRight");

  const byPointer = plain(pointer.card.read().response);
  const byKeyboard = plain(keyboard.card.read().response);
  assert.deepEqual(Object.keys(byPointer), Object.keys(byKeyboard));
  assert.deepEqual(byPointer, byKeyboard);
});

test("the keyboard instructions name the step sizes they actually use", async () => {
  const { card } = renderType("hotspot");
  await settle();

  assert.match(card.element.textContent, /5%/);
  assert.match(card.element.textContent, /1%/);
});

test("a hotspot whose image failed is still operable by keyboard", async () => {
  const { card } = renderType("hotspot", { images: "broken" });
  await settle();
  const surface = hotspotSurface(card);

  assert.ok(surface, "the control disappeared when the image did");
  assert.equal(surface.hidden, false);
  press(surface, "ArrowRight");

  assert.equal(card.read().ok, true);
});

test("labeling pins are positioned against the picture alone", async () => {
  const { card } = renderType("labeling");
  await settle();
  const surface = card.element.all().find((node) => node.className === "hotspot");

  assert.ok(!surface.textContent.includes("Full description"));
  assert.equal(surface.byTag("details").length, 0);
});

// ── Content language ──────────────────────────────────────────────────────

test("exercise content is marked with the content language", () => {
  const { card } = renderType("true_false", { locale: "en", contentLocale: "fr" });

  assert.equal(card.element.getAttribute("lang"), "fr");
});

test("interface strings inside the card stay in the interface language", () => {
  const { card } = renderType("multi_select", { locale: "en", contentLocale: "fr" });
  const hintNode = card.element.all().find((node) => node.className === "hint");

  assert.equal(hintNode.getAttribute("lang"), "en");
});

test("no language is declared when the exercise is in the reader's own language", () => {
  const { card } = renderType("true_false", { locale: "en", contentLocale: "en" });

  assert.equal(card.element.getAttribute("lang"), null);
  assert.deepEqual(
    card.element.all().filter((node) => node.getAttribute("lang")),
    []
  );
});

test("a malformed content locale is left off rather than written to the DOM", () => {
  for (const bogus of ["", "english", "e", "fr_FR!", "../fr", 42, null]) {
    const { card } = renderType("true_false", { locale: "en", contentLocale: bogus });

    assert.equal(card.element.getAttribute("lang"), null, `accepted ${bogus}`);
  }
});

test("a translation card tags its source text with the source language", () => {
  const { card, component } = renderType("translation", { locale: "en", contentLocale: "en" });
  const statement = card.element.all().find((node) => node.className === "statement");

  assert.equal(statement.getAttribute("lang"), component.payload.content.source_locale);
});

test("option labels carry the content language", () => {
  const { card } = renderType("multiple_choice", { locale: "en", contentLocale: "pt-BR" });
  const spans = card.element
    .byTag("span")
    .filter((node) => node.parentNode && node.parentNode.tagName === "label");

  assert.ok(spans.length > 0);
  for (const span of spans) {
    assert.equal(span.getAttribute("lang"), "pt-BR");
  }
});

test("the hotspot describes itself with the alt text only once there is one", async () => {
  // A dangling `aria-describedby` is a reference to nothing. Naming the fallback
  // up front meant every successfully loaded hotspot pointed at an id that did
  // not exist.
  const loaded = renderType("hotspot");
  await settle();
  const loadedSurface = hotspotSurface(loaded.card);
  const named = loadedSurface.getAttribute("aria-describedby").split(" ");
  const ids = new Set(
    loaded.card.element
      .all()
      .map((node) => node.getAttribute("id"))
      .filter(Boolean)
  );
  for (const id of named) {
    assert.ok(ids.has(id), `aria-describedby names ${id}, which is not in the card`);
  }

  const broken = renderType("hotspot", { images: "broken" });
  await settle();
  const brokenIds = new Set(
    broken.card.element
      .all()
      .map((node) => node.getAttribute("id"))
      .filter(Boolean)
  );
  const brokenNamed = hotspotSurface(broken.card).getAttribute("aria-describedby").split(" ");
  assert.equal(brokenNamed.length, 2, "the alt text was not added to the description");
  for (const id of brokenNamed) {
    assert.ok(brokenIds.has(id));
  }
});

function orderingCard(type = "sequence_order", options = {}, win = loadRenderers()) {
  const field = { sentence_order: "tokens", sequence_order: "steps", timeline: "events", process_flow: "stages" }[type];
  const component = plain(FIXTURES[type]);
  component.payload.content[field] = Array.from({ length: options.itemCount || 4 }, (_, index) => ({ id: `alias-${index}`, text: "Repeated label" }));
  const ctx = Object.assign(renderContext(win, options), options);
  const card = win.LearningStudioRenderers.render(component, ctx);
  return { win, card, ctx, rows: card.element.byTag("li"), order: () => plain(card.read().response.order) };
}

test("ordering buttons preserve row identity and directional focus through every position", () => {
  for (const type of ["sentence_order", "sequence_order", "timeline", "process_flow"]) {
    const { win, card, rows, order } = orderingCard(type);
    const down = rows[0].byTag("button")[1];
    down.focus();
    click(down);
    assert.equal(card.element.byTag("li")[1], rows[0], "the moved row must be the same node");
    assert.equal(win.document.activeElement, down);
    click(down);
    assert.equal(win.document.activeElement, down, "interior move keeps direction");
    click(down);
    const up = rows[0].byTag("button")[0];
    assert.equal(win.document.activeElement, up, "boundary chooses enabled opposite");
    assert.deepEqual(order(), ["alias-1", "alias-2", "alias-3", "alias-0"]);
    click(up); click(up); click(up);
    assert.equal(win.document.activeElement, down);
    assert.deepEqual(order(), ["alias-0", "alias-1", "alias-2", "alias-3"]);
  }
});

function pointerCard(type = "sequence_order", options = {}) {
  const win = loadRenderers(pointerEnvironment());
  const result = orderingCard(type, options, win);
  orderingGeometry(result.card);
  return { ...result, handles: result.card.element.all().filter(node => node.classList.contains("drag-handle")) };
}

test("ordering offers dedicated pointer handles only with capture support and without keyboard_only", () => {
  const { card, ctx, rows, handles } = pointerCard();
  assert.equal(handles.length, rows.length, "each row needs a dedicated handle");
  const visibleHint = card.element.all().find(n => n.classList.contains("hint") && !n.classList.contains("order-status"));
  assert.equal(visibleHint.textContent, ctx.t("card.order_hint_drag"));
  for (const handle of handles) {
    assert.equal(handle.getAttribute("tabindex"), "-1");
    assert.equal(handle.getAttribute("aria-hidden"), "true");
    assert.equal(handle.getAttribute("draggable"), null);
  }
  for (const row of rows) assert.equal(row.getAttribute("draggable"), null);
  const keyboard = pointerCard("sequence_order", { keyboardOnly: true });
  assert.equal(keyboard.handles.length, 0);
  const keyboardHint = keyboard.card.element.all().find(n => n.classList.contains("hint") && !n.classList.contains("order-status"));
  assert.equal(keyboardHint.textContent, keyboard.ctx.t("card.order_hint"));
  assert.equal(orderingCard().card.element.all().filter(n => n.classList.contains("drag-handle")).length, 0);
  const win = loadRenderers(pointerEnvironment());
  const create = win.document.createElement.bind(win.document);
  win.document.createElement = tag => { const node = create(tag); node.setPointerCapture = undefined; return node; };
  const fallback = orderingCard("sequence_order", {}, win);
  assert.equal(fallback.card.element.all().filter(n => n.classList.contains("drag-handle")).length, 0);
  click(fallback.rows[0].byTag("button")[1]);
  assert.equal(fallback.order()[1], "alias-0");

  const handleWin = loadRenderers(pointerEnvironment());
  const createHandle = handleWin.document.createElement.bind(handleWin.document);
  handleWin.document.createElement = tag => {
    const node = createHandle(tag);
    if (tag === "span") {
      let className = node.className;
      Object.defineProperty(node, "className", {
        configurable: true,
        get: () => className,
        set: value => {
          className = String(value);
          if (className.split(/\s+/).includes("drag-handle")) node.setPointerCapture = undefined;
        },
      });
    }
    return node;
  };
  const handleFallback = orderingCard("sequence_order", {}, handleWin);
  assert.equal(handleFallback.card.element.all().filter(n => n.classList.contains("drag-handle")).length, 0);
  assert.equal(card.unsupported, false);
});

test("pointer drop commits any position in each ordering family without exposing identity", () => {
  for (const type of ["sentence_order", "sequence_order", "timeline", "process_flow"]) {
    for (let from = 0; from < 4; from++) for (let to = 0; to < 4; to++) {
      const { win, card, rows, handles, order } = pointerCard(type);
      const initial = order();
      const focused = rows[1].byTag("button")[1]; focused.focus();
      const y = 100 + to * 80 + (to > from ? 70 : 2);
      pointer(handles[from], "pointerdown", 100, 120 + from * 80);
      pointer(win, "pointermove", 100, y);
      assert.deepEqual(order(), initial, "preview must not change response");
      assert.ok(rows[from].classList.contains("order-moving"), "threshold marks source");
      assert.ok(rows.some(row => row.classList.contains("insert-before") || row.classList.contains("insert-after")), "destination is visible");
      pointer(win, "pointerup", 100, y);
      const expected = initial.slice(); expected.splice(to, 0, expected.splice(from, 1)[0]);
      assert.deepEqual(order(), expected);
      assert.deepEqual(card.element.byTag("li"), expected.map(alias => rows[initial.indexOf(alias)]));
      assert.equal(win.document.activeElement, focused.disabled ? rows[1].byTag("button")[0] : focused);
      assert.equal(handles[from].hasPointerCapture(1), false);
      for (const node of card.element.all()) {
        assert.ok(!JSON.stringify(node.attributes).includes("alias-"));
        assert.ok(!JSON.stringify(node.attributes).includes("Repeated label"));
      }
      assert.ok(!card.element.serialize().includes(CANARY));
    }
  }
});

test("pointer cancellation leaves order intact and removes capture and listeners", () => {
  for (const reason of ["pointercancel", "lostpointercapture", "Escape", "outside", "tap", "cleanup", "cancel"]) {
    const { win, card, handles, rows, order } = pointerCard();
    const initial = order();
    pointer(handles[0], "pointerdown");
    if (reason !== "tap") pointer(win, "pointermove", 100, 410);
    if (reason === "Escape") win.dispatchEvent({ type: "keydown", key: "Escape", preventDefault() {} });
    else if (reason === "lostpointercapture") handles[0].releasePointerCapture(1);
    else if (reason === "outside") pointer(win, "pointerup", 390, 410);
    else if (reason === "tap") pointer(win, "pointerup", 102, 122);
    else if (reason === "cleanup" || reason === "cancel") card[reason]();
    else pointer(win, reason);
    assert.equal(handles[0].hasPointerCapture(1), false, reason);
    assert.ok(rows.every(row => !row.classList.contains("order-moving") && !row.classList.contains("insert-before") && !row.classList.contains("insert-after")), reason);
    assert.deepEqual(order(), initial, reason);
    assert.equal([...win.listeners.values()].reduce((n, set) => n + set.size, 0), 0, reason);
    pointer(win, "pointerup", 100, 410);
    assert.deepEqual(order(), initial);
    if (reason === "cleanup") {
      pointer(handles[0], "pointerdown");
      click(rows[0].byTag("button")[1]);
      assert.equal(handles[0].hasPointerCapture(1), false);
      assert.deepEqual(order(), initial, "detached controls are inert");
    }
  }
});

test("only the primary handle pointer can start or finish a gesture", () => {
  const { win, handles, rows, order } = pointerCard();
  const initial = order();
  for (const extra of [{ isPrimary: false }, { button: 2 }]) {
    pointer(handles[0], "pointerdown", 100, 120, extra);
    assert.equal(handles[0].hasPointerCapture(1), false);
  }
  pointer(rows[0], "pointerdown");
  pointer(win, "pointermove", 100, 410);
  assert.deepEqual(order(), initial);
  pointer(handles[0], "pointerdown");
  pointer(handles[1], "pointerdown", 100, 200, { pointerId: 2 });
  pointer(win, "pointermove", 100, 410, { pointerId: 2 });
  pointer(win, "pointerup", 100, 410, { pointerId: 2 });
  pointer(win, "pointercancel", 100, 410, { pointerId: 2 });
  assert.equal(handles[0].hasPointerCapture(1), true);
  assert.deepEqual(order(), initial);
  pointer(win, "pointermove", 100, 410);
  pointer(win, "pointerup", 100, 410);
  assert.equal(order()[3], initial[0]);
});

test("ordering announces positions locally and offers untimed one-step undo in each UI language", () => {
  for (const locale of ["en", "fr", "es"]) {
    const { win, card, rows, handles, order, ctx } = pointerCard("sequence_order", { locale, contentLocale: "ja" });
    const status = card.element.all().find(n => n.classList.contains("order-status"));
    const regions = card.element.all().filter(n => n.getAttribute("role") === "status");
    const undo = card.element.byTag("button").find(n => n.classList.contains("order-undo"));
    assert.equal(regions.length, 2, "card needs alternating status regions");
    assert.ok(regions.every(region => region.getAttribute("aria-live") === "polite"));
    assert.ok(regions.every(region => region.getAttribute("lang") === locale));
    assert.equal(undo.getAttribute("lang"), locale);
    assert.equal(undo.disabled, true);
    assert.equal(undo.textContent, ctx.t("card.undo_move"));
    assert.notEqual(undo.textContent, "card.undo_move");
    const initial = order();
    click(rows[0].byTag("button")[1]);
    assert.equal(status.textContent, ctx.t("card.moved", { from: 1, to: 2, count: 4 }));
    assert.ok(!status.textContent.includes("Repeated label"));
    assert.equal(undo.disabled, false);
    const previous = order();
    pointer(handles[0], "pointerdown", 100, 200);
    pointer(win, "pointermove", 100, 410);
    pointer(win, "pointerup", 100, 410);
    assert.equal(status.textContent, ctx.t("card.moved", { from: 2, to: 4, count: 4 }));
    // There is no expiry timer; frame progression cannot spend Undo.
    for (let n = 0; n < 100; n++) win.frame();
    undo.focus(); click(undo);
    assert.deepEqual(order(), previous);
    assert.equal(status.textContent, ctx.t("card.move_undone"));
    assert.equal(undo.disabled, true);
    assert.ok(rows[0].contains(win.document.activeElement), "undo leaves focus on the restored row");
    click(undo);
    assert.deepEqual(order(), previous, "only the last move can be undone");
    click(rows[0].byTag("button")[0]);
    assert.deepEqual(order(), initial);
    pointer(handles[0], "pointerdown"); pointer(win, "pointermove", 100, 410); pointer(win, "pointercancel");
    assert.equal(status.textContent, ctx.t("card.move_cancelled"));
    assert.equal(undo.disabled, false, "cancelling does not discard last committed inverse");
    click(undo);
    assert.deepEqual(order(), previous);
    card.cleanup();
    assert.equal(undo.disabled, true);
    assert.equal(status.textContent, "");
  }
});

test("repeated ordering feedback alternates live regions and same-position drops are explicit", () => {
  const repeated = pointerCard();
  const regions = repeated.card.element.all().filter(n => n.getAttribute("role") === "status");
  assert.equal(regions.length, 2);
  click(repeated.rows[0].byTag("button")[1]);
  const first = regions.find(region => region.textContent);
  const firstText = first.textContent;
  click(repeated.rows[1].byTag("button")[1]);
  const second = regions.find(region => region.textContent);
  assert.notEqual(second, first, "an identical sentence must still mutate a different live region");
  assert.equal(second.textContent, firstText);

  const unchanged = pointerCard();
  const unchangedRegions = unchanged.card.element.all().filter(n => n.getAttribute("role") === "status");
  pointer(unchanged.handles[0], "pointerdown", 100, 120);
  pointer(unchanged.win, "pointermove", 100, 130);
  pointer(unchanged.win, "pointerup", 100, 130);
  assert.equal(
    unchangedRegions.map(region => region.textContent).join(""),
    unchanged.ctx.t("card.position_unchanged", { position: 1, count: 4 }),
  );
});

test("ordering autoscroll is bounded at unobscured edges and stops on every exit", () => {
  for (const exit of ["pointerup", "pointercancel", "lostpointercapture", "Escape", "cleanup", "cancel"]) {
    const { win, card, handles, order } = pointerCard();
    const footer = win.document.createElement("footer"); footer.id = "actions";
    footer.getBoundingClientRect = () => ({ top: 600, bottom: 800, height: 200 });
    win.document.body.appendChild(footer);
    win.visualViewport = { offsetTop: 30, height: 730 };
    let offset = 0;
    orderingGeometry(card, () => 450 - offset);
    win.scrollBy = options => { win.scrolls.push(options); offset += options.top; };
    const initial = order();
    pointer(handles[0], "pointerdown", 100, 470);
    pointer(win, "pointermove", 100, 590);
    assert.equal(win.frames.size, 1, "edge schedules autoscroll above sticky footer");
    for (let i = 0; i < 8; i++) win.frame();
    assert.ok(win.scrolls.length > 0);
    assert.ok(win.scrolls.every(s => s.top > 0 && s.top <= 12 && s.behavior === "instant"));
    assert.deepEqual(order(), initial);
    if (exit === "Escape") win.dispatchEvent({ type: "keydown", key: "Escape", preventDefault() {} });
    else if (exit === "lostpointercapture") handles[0].releasePointerCapture(1);
    else if (exit === "cleanup" || exit === "cancel") card[exit]();
    else pointer(win, exit, 390, 590);
    assert.equal(win.frames.size, 0, exit);
    const count = win.scrolls.length; win.frame();
    assert.equal(win.scrolls.length, count);
    assert.deepEqual(order(), initial);
  }
});

test("ordering autoscroll respects visual viewport, list bounds, and reduced motion", () => {
  const { win, card, handles } = pointerCard("sequence_order", { reducedMotion: true });
  win.matchMedia = () => ({ matches: true });
  win.visualViewport = { offsetTop: 100, height: 500 };
  orderingGeometry(card, () => -20);
  pointer(handles[1], "pointerdown", 100, 180);
  pointer(win, "pointermove", 100, 115);
  win.frame();
  assert.ok(win.scrolls.some(s => s.top < 0 && s.top >= -12 && s.behavior === "instant"));
  for (const [x, y] of [[100, 90], [390, 115], [100, 300], [100, 610]]) {
    pointer(win, "pointermove", x, y);
    assert.equal(win.frames.size, 0, `${x},${y} must not autoscroll`);
  }
  pointer(win, "pointerup", 100, 610);
  assert.deepEqual(plain(card.read().response.order), ["alias-0", "alias-1", "alias-2", "alias-3"], "occluded drop cancels");
});

test("ordering excludes the computed safe-area inset from drops", () => {
  const { win, card, handles, order, ctx } = pointerCard();
  const initial = order();
  const status = card.element.all().find(n => n.classList.contains("order-status"));
  win.visualViewport = { offsetTop: 30, height: 700 };
  win.getComputedStyle = () => ({ paddingTop: "40px" });
  orderingGeometry(card, () => 0);
  pointer(handles[1], "pointerdown", 100, 120);
  pointer(win, "pointermove", 100, 60);
  pointer(win, "pointerup", 100, 60);
  assert.deepEqual(order(), initial);
  assert.equal(status.textContent, ctx.t("card.move_cancelled"));
});

test("ordering autoscroll stops when the document cannot move farther", () => {
  const { win, card, handles } = pointerCard();
  const footer = win.document.createElement("footer"); footer.id = "actions";
  footer.getBoundingClientRect = () => ({ top: 600, bottom: 800, height: 200 });
  win.document.body.appendChild(footer);
  orderingGeometry(card, () => 450);
  win.scrollY = 500;
  win.scrollBy = options => { win.scrolls.push(options); };
  pointer(handles[0], "pointerdown", 100, 470);
  pointer(win, "pointermove", 100, 590);
  assert.equal(win.frames.size, 1);
  win.frame();
  assert.equal(win.frames.size, 0, "a no-op scroll must not schedule another frame");
});

test("pointer moves keep focus on an enabled control of the same row at a boundary", () => {
  const { win, rows, handles } = pointerCard();
  const [up, down] = rows[1].byTag("button");
  down.focus();
  pointer(handles[1], "pointerdown", 100, 200);
  pointer(win, "pointermove", 100, 410);
  pointer(win, "pointerup", 100, 410);
  assert.equal(win.document.activeElement, up, "disabled focused direction needs its enabled opposite");

  const hiddenFocus = pointerCard();
  hiddenFocus.handles[1].focus();
  pointer(hiddenFocus.handles[1], "pointerdown", 100, 200);
  pointer(hiddenFocus.win, "pointermove", 100, 410);
  pointer(hiddenFocus.win, "pointerup", 100, 410);
  assert.ok(hiddenFocus.rows[1].contains(hiddenFocus.win.document.activeElement));
  assert.notEqual(hiddenFocus.win.document.activeElement, hiddenFocus.handles[1]);
  assert.notEqual(hiddenFocus.win.document.activeElement.getAttribute("aria-hidden"), "true");
});

test("Escape before movement cancels capture without swallowing the key", () => {
  const { win, handles, order } = pointerCard();
  const initial = order();
  let prevented = false;
  pointer(handles[0], "pointerdown");
  win.dispatchEvent({ type: "keydown", key: "Escape", preventDefault() { prevented = true; } });
  assert.equal(prevented, false);
  assert.equal(handles[0].hasPointerCapture(1), false);
  assert.equal([...win.listeners.values()].reduce((n, entries) => n + entries.size, 0), 0);
  assert.deepEqual(order(), initial);
});

test("a long list can reach its last destination through autoscroll in one gesture", () => {
  const { win, card, handles, order } = pointerCard("sequence_order", { itemCount: 12 });
  let offset = 0;
  orderingGeometry(card, () => 100 - offset);
  win.scrollBy = options => { offset += options.top; };
  const initial = order();
  pointer(handles[0], "pointerdown");
  pointer(win, "pointermove", 100, 790);
  for (let n = 0; n < 400 && win.frames.size; n++) win.frame();
  assert.equal(win.frames.size, 0, "autoscroll stops when the list fits above the lower edge");
  assert.ok(offset > 200);
  assert.deepEqual(order(), initial);
  pointer(win, "pointerup", 100, 790);
  assert.deepEqual(order(), [...initial.slice(1), initial[0]]);
});

test("capture refusal leaves buttons available and no transient work behind", () => {
  const { win, handles, rows, order } = pointerCard();
  handles[0].setPointerCapture = () => { throw new Error("capture unavailable"); };
  pointer(handles[0], "pointerdown");
  pointer(win, "pointermove", 100, 410);
  assert.equal(win.frames.size, 0);
  assert.equal([...win.listeners.values()].reduce((n, entries) => n + entries.size, 0), 0);
  click(rows[0].byTag("button")[1]);
  assert.equal(order()[1], "alias-0");
});

test("tap and same-position drop leave the last committed Undo available", () => {
  const { win, card, handles, rows, order } = pointerCard();
  const initial = order();
  click(rows[0].byTag("button")[1]);
  const undo = card.element.byTag("button").find(n => n.classList.contains("order-undo"));
  pointer(handles[0], "pointerdown", 100, 200);
  pointer(win, "pointerup", 101, 201);
  pointer(handles[0], "pointerdown", 100, 200);
  pointer(win, "pointermove", 100, 240);
  pointer(win, "pointerup", 100, 240);
  click(undo);
  assert.deepEqual(order(), initial);
});
